apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: synthia.azurecr.io/synthiarosetta/testapp:v1
        ports:
        - containerPort: 9999
---        
apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  type: LoadBalancer
  ports:
  - port: 9999
  selector:
    app: testapp
