apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
        - name: testapp1
          image: testing.azurecr.io/synthiarosetta/testapp1:v1
          ports:
            - containerPort: 9999
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 15
            periodSeconds: 20
---   
apiVersion: v1
kind: Service
metadata:
  name: testapp1
  labels:
    app: testapp1
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 80
  selector:
    app: testapp1
